### ISSUE TITLE
it is so interesting not maintained anymore??

### ISSUE THREAD

**Issue by Altai01** [vivi90/python-vmc#1]
I come from this https://github.com/Arthur151/ROMP/issues/193.i also use blender to control model

**Comment by vivi90** [comment]
@Altai01 Yes, it's interesting.
I still need it for another project.
But my deadline ends on 30th of June 2022.
And as you can see in the [README](https://github.com/vivi90/python-vmc#readme) there is still an bug, i am not able to solve.

**Comment by vivi90** [comment]
@Altai01 Deadline extended until 1st of August 2022 in the meanwhile.
So okay, let's try again..
