### ISSUE TITLE
I need driving characters in Unreal Engine

### ISSUE THREAD

**Issue by SlimeVRX** [vivi90/python-vmc#3]
Hello @vivi90 

I read your comment

![image](https://user-images.githubusercontent.com/99313947/197716364-86e6ca63-aab6-4965-844b-0b7246eef85a.png)

Link: https://github.com/Arthur151/ROMP/issues/172#issuecomment-1214918118

I need driving characters in Unreal Engine

Can you support me?

Thank you very much!

Best regards,

Tin Nguyen Thanh

**Comment by SlimeVRX** [comment]
Hi @vivi90 

I want to tell you about the research I'm working on. Research on posture estimation from 6 sensors.
After releasing the V1 version based on the TransPose article, now I have released the V2 version based on the PIP article, with many improvements, and smoother motion. 

This is my latest test in Unity

Link 1: https://drive.google.com/file/d/1ZTnN37yazS60ipiwx6R2VwaiZ3wDMCw9/view
Link 2: https://drive.google.com/file/d/19UHiG1n5cqElEofuXWPYcXClD5GKmPqG/view

Data is processed in Python and then sent through Unity using Socket library
The position of 24 skeletons is transferred to the Unity-chan model

![image](https://user-images.githubusercontent.com/99313947/197742816-f24f5330-c046-4503-9e51-2ce43aec7151.png)

Currently, I want to create a plug-in to send skeleton data from Python to Metahuman, can you help me? I am familiar with Python language
I'm not familiar with Unreal, I started learning how to use Unreal
I can send Python and Unity code for your reference.

Please help me!

Best regards,

Tin Nguyen Thanh

**Comment by vivi90** [comment]
@SlimeVRX See: https://codeberg.org/vivi90/python-vmcp/issues/2#issuecomment-660073

**Comment by SlimeVRX** [comment]
Hi @vivi90
I transfer data from Python to Unreal, here is the video. Thanks a lot
Video: https://drive.google.com/file/d/1Z1MuacdF-hRbXLZxwUz5q2VpDhdEbHsJ/view
Models in order are Metahuman, SMPL, FBX

**Comment by vivi90** [comment]
@SlimeVRX 
> Video: https://drive.google.com/file/d/1Z1MuacdF-hRbXLZxwUz5q2VpDhdEbHsJ/view

Nice.
This motions seems to be fluent, but the overlay says 2 FPS?

PS: Sorry for editing your comment by accident xD

**Comment by SlimeVRX** [comment]
Hi @vivi90 

I want to thank you very much. The hardest part of the job is sending Python test data to Vseeface using the VMC Protocol. I used your code.

Do you know any way to send data directly from Python to Unreal? (do not use VseeFace)

Best regards,

Tin Nguyen Thanh

**Comment by vivi90** [comment]
@SlimeVRX 
> Do you know any way to send data directly from Python to Unreal? (do not use VseeFace)

See: https://codeberg.org/vivi90/python-vmcp/issues/2#issuecomment-663820

**Comment by SlimeVRX** [comment]
Sorry @vivi90  
I just now read your response on codeberg.org. I will reply on that page.

**Comment by SlimeVRX** [comment]
Hi @vivi90 

VMCP worked, see more on codeberg.org

**Comment by SlimeVRX** [comment]
Hi @vivi90 

I was able to pass the SMPL skeleton data into Unreal. I want to continue hand data transmission. Can you help me develop?

I created an issue here: https://codeberg.org/vivi90/python-vmcp/issues/4

**Comment by zhanghongyong123456** [comment]
> Hi @vivi90
> 
> I want to thank you very much. The hardest part of the job is sending Python test data to Vseeface using the VMC Protocol. I used your code.
> 
> Do you know any way to send data directly from Python to Unreal? (do not use VseeFace)
> 
> Best regards,
> 
> Tin Nguyen Thanh

I tried to use vmcps project and VMC4UE plug-in to drive a character, but this problem occurred. What should I do? I think it might be Bone Position Synchronize, but I could not find this option in UE.
![image](https://github.com/vivi90/python-vmc/assets/48466610/118ae44b-685b-490c-a32f-e982b58b5ca0)
What should I do and look forward to your reply

**Comment by SlimeVRX** [comment]
Yes, I also got the same error.
The workaround is that you need to retarget motion to another character, the retargeted character will not fail

**Comment by zhanghongyong123456** [comment]
> Yes, I also got the same error. The workaround is that you need to retarget motion to another character, the retargeted character will not fail

I don't understand what you mean. Could you explain how to solve it，Thank you very much for your reply， 
 for  use   VMC4UE     i  using  unity   get  VMC4UEVRMMapping ， like this   video  https://www.youtube.com/watch?v=2h2wkowg0oA  
![image](https://github.com/vivi90/python-vmc/assets/48466610/13ba5906-9ae2-4bb7-8f5c-11247194d273)

So you said to change the role, I don't quite understand how to operate, can you give me the implementation details or pictures

**Comment by SlimeVRX** [comment]
Yes, You do right.

You need to retarget from the current character to another character. (current characte is error, another character is not error)

You can see retargeting from character to character [here](https://youtu.be/tXy_n7hIMEE)

**Comment by zhanghongyong123456** [comment]
> Yes, You do right.
> 
> You need to retarget from the current character to another character. (current characte is error, another character is not error)
> 
> You can see retargeting from character to character [here](https://youtu.be/tXy_n7hIMEE)

The video I refer(https://www.youtube.com/watch?v=2h2wkowg0oA) to also works like this, and the result is wrong.  i use  this projct(https://codeberg.org/vivi90/vmcps  not  use other project(https://codeberg.org/vivi90/python-vmcp))  get   data
![image](https://github.com/vivi90/python-vmc/assets/48466610/40eb8e1a-0755-424c-aff2-f4fc306b96ee)
![image](https://github.com/vivi90/python-vmc/assets/48466610/26c0c6cc-d8a8-4287-aa85-9a3151cb8e82)

**Comment by zhanghongyong123456** [comment]
I  use   VSeeFace  get date  it‘s   ok，when   use vmcps get  data   have this  error,(You need to retarget from the current character to another character)   i  think  i have  do it 
![image](https://github.com/vivi90/python-vmc/assets/48466610/906d2652-77f4-46c3-8f85-396b6044911a)
Select the correct mesh for Mapping matching here

**Comment by vivi90** [comment]
> I use VSeeFace get date it‘s ok，when use vmcps get data have this error,(You need to retarget from the current character to another character) i think i have do it ![image](https://user-images.githubusercontent.com/48466610/243578242-906d2652-77f4-46c3-8f85-396b6044911a.png) Select the correct mesh for Mapping matching here

Thanks for your solution 👍
May you please also add an english screenshot?
Since your Unreal UI is in chinese and i want to add some notes to the readme to help also other users.

**Comment by zhanghongyong123456** [comment]
> 1.  if bev can be used to get data (instead of romp)

Should work with some small modifications. You are free to edit the code.

> 2. and can multiple drivers be used (more than one person drives)

If you mean tracking of multiple persons:
Yes, romp does support this.
But the VMC protocol not.
To do this, you require multiple VMC protocol channels.
My vmcp package supports this.
The vmcps example script supports this also with some small modifications.
But it depends on the implementation of your used Unity/Unreal plugin.
Not tested yet.

**Comment by SlimeVRX** [comment]
> 2.  can multiple drivers be used (more than one person drives).

I am also interested in this, is it possible? multi-input for multi-character

**Comment by zhanghongyong123456** [comment]
> > 2. can multiple drivers be used (more than one person drives).
> 
> I am also interested in this, is it possible? multi-input for multi-character

HI , Can you tell me about your implementation process in detail? I am still stuck on this question

**Comment by vivi90** [comment]
@zhanghongyong123456 Sorry for editing your comment 🥺
Was an mistake, while writing on my mobile phone.

@zhanghongyong123456 @SlimeVRX 
> 1.  if bev can be used to get data (instead of romp)

Should work with some small modifications. You are free to edit the code.

> 2. and can multiple drivers be used (more than one person drives)

If you mean tracking of multiple persons:
Yes, romp does support this.
But the VMC protocol not.
To do this, you require multiple VMC protocol channels.
My vmcp package supports this.
The vmcps example script supports this also with some small modifications.
But it depends on the implementation of your used Unity/Unreal plugin.
Not tested yet.

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 Sorry for editing your comment 🥺 Was an mistake, while writing on my mobile phone.
> 
> @zhanghongyong123456 @SlimeVRX
> 
> > 1. if bev can be used to get data (instead of romp)
> 
> Should work with some small modifications. You are free to edit the code.
> 
> > 2. and can multiple drivers be used (more than one person drives)
> 
> If you mean tracking of multiple persons: Yes, romp does support this. But the VMC protocol not. To do this, you require multiple VMC protocol channels. My vmcp package supports this. The vmcps example script supports this also with some small modifications. But it depends on the implementation of your used Unity/Unreal plugin. Not tested yet.

OK   thank you ,When I implement the UE project, I will write a UE related process for your readme file

**Comment by zhanghongyong123456** [comment]
> Yes, You do right.
> 
> You need to retarget from the current character to another character. (current characte is error, another character is not error)
> 
> You can see retargeting from character to character [here](https://youtu.be/tXy_n7hIMEE)

i use yours video, VSeeFace   can use,but use vmcp  have error,Look forward to your help, thank you

**Comment by SlimeVRX** [comment]
You need to watch the next video tutorial 02 -> 03. [Here](https://youtu.be/iUYOa3m_ekU)

Follow the instructions of this video, retarget motion from Vroid model to Metahuman, the Vroid model will fail, but the Metahuman model will not fail.

**Comment by zhanghongyong123456** [comment]
> You need to watch the next video tutorial 02 -> 03. [Here](https://youtu.be/iUYOa3m_ekU)
> 
> Follow the instructions of this video, retarget motion from Vroid model to Metahuman, the Vroid model will fail, but the Metahuman model will not fail.

Instead of matahuman, how do you get VRMMapping，
![image](https://github.com/vivi90/python-vmc/assets/48466610/516cd02d-3e94-4a9a-9c1a-2959f0662adb)

**Comment by SlimeVRX** [comment]
Your VMC4UE is working correctly, please skip it!

Continue with Retarget, Retarget motion from Vroid to Metahuman (or another character)

Metahuman (or another character) will work

**Comment by zhanghongyong123456** [comment]
> Your VMC4UE is working correctly, please skip it!
> 
> Continue with Retarget, Retarget motion from Vroid to Metahuman (or another character)
> 
> Metahuman (or another character) will work
The replacement of matahuman is still wrong, I think it is the problem of data mismatch, but I do not know how to modify it
![image](https://github.com/vivi90/python-vmc/assets/48466610/ebbe8a3c-33e2-4052-b2a6-ae6bdbcc7c50)

**Comment by SlimeVRX** [comment]
Are you sure to follow video tutorial 03? Retarget motion from Vroid to Metahuman

**Comment by zhanghongyong123456** [comment]
> Are you sure to follow video tutorial 03? Retarget motion from Vroid to Metahuman

It is according to this operation, I use VSeeFace is working, switch to vmcp there is an error,

**Comment by zhanghongyong123456** [comment]
> > Are you sure to follow video tutorial 03? Retarget motion from Vroid to Metahuman
> 
> It is according to this operation, I use VSeeFace is working, switch to vmcp there is an error,
Can you help me remotely? I've been stuck here for a long time

**Comment by SlimeVRX** [comment]
Can you show me your skeleton retarget 2 mapping file? I want to see if retarget has any errors?

**Comment by SlimeVRX** [comment]
Like image

![image](https://github.com/vivi90/python-vmc/assets/99313947/e59b76c8-00a3-4537-8a61-4fb6997a3e30)

![image](https://github.com/vivi90/python-vmc/assets/99313947/d938d59b-fc24-4050-acf4-0cbb903599c5)

**Comment by zhanghongyong123456** [comment]
> Can you show me your skeleton retarget 2 mapping file? I want to see if retarget has any errors?

can you  download  todesk to Control my computer ， My   ID  643391818    password:  008763

**Comment by SlimeVRX** [comment]
ok

**Comment by zhanghongyong123456** [comment]
> ok

thank you  very much

**Comment by SlimeVRX** [comment]
Please check again anydesk, I don't find your computer

**Comment by zhanghongyong123456** [comment]
> Please check again anydesk, I don't find your computer

小四邀请您进行远程控制
ToDesk设备代码:643 391 818
临时密码:008763
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=5rLAe4CEL1Y5DZlaNfjD-

**Comment by SlimeVRX** [comment]
Sorry, I don't connect

![Capt123ure](https://github.com/vivi90/python-vmc/assets/99313947/82cbe42c-6471-4623-b678-8e3113337297)

**Comment by SlimeVRX** [comment]
Sorry, I confused todesk and anydesk

**Comment by zhanghongyong123456** [comment]
> Sorry, I don't connect
> 
> ![Capt123ure](https://user-images.githubusercontent.com/99313947/243897612-82cbe42c-6471-4623-b678-8e3113337297.PNG)

Maybe it's a regional issue, and my colleagues can connect

**Comment by SlimeVRX** [comment]
Sorry, I don't have number phone China to verify ToDesk

**Comment by zhanghongyong123456** [comment]
> Sorry, I don't have number phone China to verify ToDesk

Do you have any other ways to help me，can you give me your test project

**Comment by SlimeVRX** [comment]
> Like image
> 
> ![image](https://user-images.githubusercontent.com/99313947/243896484-e59b76c8-00a3-4537-8a61-4fb6997a3e30.png)
> 
> ![image](https://user-images.githubusercontent.com/99313947/243896526-d938d59b-fc24-4050-acf4-0cbb903599c5.png)

Please check again

**Comment by zhanghongyong123456** [comment]
> > Like image
> > ![image](https://user-images.githubusercontent.com/99313947/243896484-e59b76c8-00a3-4537-8a61-4fb6997a3e30.png)
> > ![image](https://user-images.githubusercontent.com/99313947/243896526-d938d59b-fc24-4050-acf4-0cbb903599c5.png)
> 
> Please check again

it‘s  ok， can you upload   a UE  test project on your github

**Comment by SlimeVRX** [comment]
You can connect with my friend in China, I hope he can help you
![image](https://github.com/vivi90/python-vmc/assets/99313947/7e062312-51ea-496e-8bb4-ce94b4a48f87)

**Comment by zhanghongyong123456** [comment]
> You can connect with my friend in China, I hope he can help you ![image](https://user-images.githubusercontent.com/99313947/243900319-7e062312-51ea-496e-8bb4-ce94b4a48f87.png)

OK,you  have QQ ? Maybe remotely via QQ

**Comment by SlimeVRX** [comment]
I have WeChat
![image](https://github.com/vivi90/python-vmc/assets/99313947/f4660f5c-ea00-4371-b930-8a5fd31f0668)

**Comment by zhanghongyong123456** [comment]
> > I use VSeeFace get date it‘s ok，when use vmcps get data have this error,(You need to retarget from the current character to another character) i think i have do it ![image](https://user-images.githubusercontent.com/48466610/243578242-906d2652-77f4-46c3-8f85-396b6044911a.png) Select the correct mesh for Mapping matching here
> 
> Thanks for your solution 👍 May you please also add an english screenshot? Since your Unreal UI is in chinese and i want to add some notes to the readme to help also other users.

Implement UE-driven MetaHuman step process, here, you can see what needs to be modified https://codeberg.org/vivi90/vmcps/issues/3

**Comment by SlimeVRX** [comment]
Nice work!

**Comment by zhanghongyong123456** [comment]
> Nice work!
[thank you very much for your help](javascript:;)，
But there are a few problems: 1) fps is very low, how to improve it, 2) how to replace the romp model with the bev model; 3. How to deal with multiple people

**Comment by SlimeVRX** [comment]
1. I don't check FPS. My test [video](https://youtu.be/U5kN4Fcjxos)
2. Output romp is SMPL, you can replace any model SMPL output
3. Support multi people: Please ask @vivi90 
```
If you mean tracking of multiple persons:
Yes, romp does support this.
But the VMC protocol not.
To do this, you require multiple VMC protocol channels.
My vmcp package supports this.
The vmcps example script supports this also with some small modifications.
But it depends on the implementation of your used Unity/Unreal plugin.
Not tested yet.
```

**Comment by zhanghongyong123456** [comment]
> 1. I don't check FPS. My test [video](https://youtu.be/U5kN4Fcjxos)
> 2. Output romp is SMPL, you can replace any model SMPL output
> 3. Support multi people: Please ask @vivi90
> 
> ```
> If you mean tracking of multiple persons:
> Yes, romp does support this.
> But the VMC protocol not.
> To do this, you require multiple VMC protocol channels.
> My vmcp package supports this.
> The vmcps example script supports this also with some small modifications.
> But it depends on the implementation of your used Unity/Unreal plugin.
> Not tested yet.
> ```

Wow, that's cool. You're very handsome，Why is your video so smooth，I mean using bev not romp
![image](https://github.com/vivi90/python-vmc/assets/48466610/368011dc-989f-43c1-8926-7da71025fd4a)

**Comment by SlimeVRX** [comment]
> I mean using bev not romp

Yes, Bev and Romp output is SMPL format

> Why is your video so smooth?

Can you make a video about the problem you're having?

**Comment by zhanghongyong123456** [comment]
> > I mean using bev not romp
> 
> Yes, Bev and Romp output is SMPL format
> 
> > Why is your video so smooth?
> 
> Can you make a video about the problem you're having?
this  my test，I only have a USB camera to capture video
https://www.youtube.com/watch?v=YzuyBLsNrUo

**Comment by SlimeVRX** [comment]
Hi, Can you put the video predict with ROMP on the side to compare with the video from Unreal? This will make it easier to see the problem

**Comment by zhanghongyong123456** [comment]
> 

I  find  a error,like  this and that? when  romp  fps=30  UE fps only 8,when  UE fps  40 romp only 5 fps
![2fafd7de5b6c4e40b8143af88b04a0a](https://github.com/vivi90/python-vmc/assets/48466610/90993c65-0f5c-467a-b9ef-edca42a4b06b)
![46290e1f83b4cbf2d8734a21cb06433](https://github.com/vivi90/python-vmc/assets/48466610/d493792f-a09a-4f94-beea-a7b52fe37c6c)

**Comment by SlimeVRX** [comment]
What you say is difficult to imagine, 
I need a benchmark to compare, 
Please use VseeFace, I will compare VseeFace and Unreal

**Comment by vivi90** [comment]
Thanks you for benchmarking this 🙂

Bye the way, since the VMC protocol messages needs top be delivered as soon as possible, the underlying OSC/Ethernet implementation has also an significant impact on FPS.

As you can see at the diagram on  https://pypi.org/project/vmcp, the `vmcp` package currently uses the `osc4py3` implementation.
But you can easily replace it by another one.

**Comment by zhanghongyong123456** [comment]
> 



> Thanks you for benchmarking this 🙂
> 
> Bye the way, since the VMC protocol messages needs top be delivered as soon as possible, the underlying OSC/Ethernet implementation has also an significant impact on FPS.
> 
> As you can see at the diagram on https://pypi.org/project/vmcp, the `vmcp` package currently uses the `osc4py3` implementation. But you can easily replace it by another one.

1. What can be replaced（osc4py3）; 2. Transfer multi-person data Where do I change the code because I'm not sure I understand the project flow

**Comment by vivi90** [comment]
> 1. What can be replaced（osc4py3)


The backend (`osc4py3`) imports beginns here:
https://codeberg.org/vivi90/python-vmcp/src/branch/main/src/vmcp/osc/backend

So you can easily copy this code and edit it to use for example `python-osc` instead of `osc4py3`.

`osc4py3` is very stable but it's also very old.
Maybe `python-osc` have an better transfer speed since its fresher, i don't know.


> 2. Transfer multi-person data [..]


In the config file (https://codeberg.org/vivi90/vmcps/src/branch/main/romp.yml) you see the setting `subject`.
Thats the number of the person to track If there are more than one in the picture/video source.

The video source (If it's a webcam) is set by `source` there.

So the most easier way (without programming skills) to track multiple people are:
 1. Copy the source (webcams in Windows for example with the "SplitCam" software).
 2. Create 2 config files with different `subject` and `source` and connection `port` values
 3. Create 2 scripts and edit they in line 171 (https://codeberg.org/vivi90/vmcps/src/commit/6024aa2e25a2baa06300ad6d832c33ae006ce9db/romp_vmcp.py#L171).
 3. Start both scripts at the same time.

**Comment by zhanghongyong123456** [comment]
> > 1. What can be replaced（osc4py3)
> 
> The backend (`osc4py3`) imports beginns here: https://codeberg.org/vivi90/python-vmcp/src/branch/main/src/vmcp/osc/backend
> 
> So you can easily copy this code and edit it to use for example `python-osc` instead of `osc4py3`.
> 
> `osc4py3` is very stable but it's also very old. Maybe `python-osc` have an better transfer speed since its fresher, i don't know.
> 
> > 2. Transfer multi-person data [..]
> 
> In the config file (https://codeberg.org/vivi90/vmcps/src/branch/main/romp.yml) you see the setting `subject`. Thats the number of the person to track If there are more than one in the picture/video source.
> 
> The video source (If it's a webcam) is set by `source` there.
> 
> So the most easier way (without programming skills) to track multiple people are:
> 
> 1. Copy the source (webcams in Windows for example with the "SplitCam" software).
> 2. Create 2 config files with different `subject` and `source` and connection `port` values
> 3. Create 2 scripts and edit they in line 171 (https://codeberg.org/vivi90/vmcps/src/commit/6024aa2e25a2baa06300ad6d832c33ae006ce9db/romp_vmcp.py#L171).
> 4. Start both scripts at the same time.

I want to replace   osc4py3 to python-osc，but  i can't understand the function of backend. What is the relationship between osc, backend (osc4py3), and python-osc
![image](https://github.com/vivi90/python-vmc/assets/48466610/ce43e3aa-b704-4a19-844a-8cdbb558b66f)
I tested python-osc code and found only two lines of client code
![image](https://github.com/vivi90/python-vmc/assets/48466610/e3590752-eed5-46c0-9ddf-b14e7e379e70)
